# https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
dist: xenial
sudo: true

language: "python"
python:
  - "3.7"
install:
  - "pipenv install --dev"
script:
  - "pipenv run test && pipenv run freeze"
env:
  global:
    - secure: "G+uIvwFZuwToSLPQryVhXRL16GYznBN7AcKcf1nP2FaTrBp4pVnZuNIrQ1eyuAGgwICoOled9EluT7T+ABqZHLUUoU5lymFuQwQPgZyOKZQXF3USAuwa2kqcXRp477xrhUANPHk3qR1qeT+WCCRyfo9YB3AdXHD1p5JItsL2Ar0="
deploy:
  provider: "script"
  script: "pipenv run deploy"
  on:
    branch: "master"
    repo: "pyvec/pyvec.org"
