language: python
python:
  - "3.5"
script:
  - "echo 'No tests!'"
env:
  global:
    - secure: "GoeDHoZRSku/plR4ENpg5KcuFJtLjFewDPSEvUAow/46CPPI++NU8T8be+B8+T+8gblEASRdT8uRHt2Ow0geQwRmYqAwNYUqyJ6hJmMgrDGQYDySNwDEJrZmAET28SdrI51TossiFBqe4DbpnY3OwjHP25zJrPT3FTfv5K1WmZg="
deploy:
  provider: "script"
  script: "python pyvec.py deploy"
  on:
    branch: "master"
    repo: "pyvec/pyvec.org"
